name: Generate
"on":
  workflow_dispatch:
    inputs:
      force:
        description: Force the generation of the SDKs
        type: boolean
        default: false
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v10
    with:
      force: ${{ github.event.inputs.force }}
      languages: |-
        - go: go-client-sdk
        - typescript: typescript-client-sdk
        - java: java-client-sdk
        - python: python-client-sdk
      openapi_doc_location: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml
      speakeasy_version: latest
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
