name: Generate

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force the generation of the SDKs"
        type: boolean
        default: false
  schedule:
    - cron: 0 0 * * * # Runs every day at midnight

jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-generation.yaml@v10 # Import the sdk generation workflow which will handle the generation of the SDKs and publishing to the package managers
    with:
      force: ${{ github.event.inputs.force }}
      speakeasy_version: latest
      openapi_doc_location: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml
      languages: |-
        - go: go-client-sdk
        - typescript: typescript-client-sdk
        - java: java-client-sdk
        - python: python-client-sdk
    secrets:
      speakeasy_api_key: ${{ secrets.SPEAKEASY_PROD_API_KEY }}
      github_access_token: ${{ secrets.GITHUB_TOKEN }}